### ISSUE TITLE
What is the autofocus option for?

### ISSUE THREAD

**Issue by Moosems** [rdbende/tkcode#10]

**Comment by rdbende** [comment]
If `True`, the codebox will automatically gain input focus, when created.

**Comment by Moosems** [comment]
I'm still a bit confused

**Comment by rdbende** [comment]
So for example, if you have a plain textbox, you have to click into it to be able to start typing. However when using the `autofocus` option on a codebox, you can start typing immediately when the window appears.

**Comment by Moosems** [comment]
Thank you!
