### ISSUE TITLE
Unable to change language of CodeEditor

### ISSUE THREAD

**Issue by halfrender** [rdbende/tkcode#5]
so i was just trying to change the language in the CodeEditor by:
```python3
def openfile():
    filepath = askopenfilepath(.....)
    extension = filepath.split('.')[-1]
    editor["language"] = identify_extension(extension)
```
where editor is the `CodeEditor()` and `identify_extension()` returns the programming language name for the extension..

but when i ran `openfile()`
the language of the CodeEditor didn't change at all.. and was still the default `python` for every extension..

**Comment by rdbende** [comment]
Thanks for reporting this. It's a crazy idiot mistake in the `__setitem__` method. And since I don't write unittests, and I don't even try the dict like configuration, I never get an error.

However, 
```python
editor.config(language=identify_extension(extension))
```
should work.

**Comment by Whirlpool-Programmer** [comment]
but still it didn't work..

**Comment by ayuvius** [comment]
it does not work..

**Comment by rdbende** [comment]
Could you show me what kind of error you get?

**Comment by Whirlpool-Programmer** [comment]
no, i didn't get any errors..
just it didn't work..
(if you want to dive into the code then here it is: https://github.com/Whirlpool-Programmer/WhirlEdit/blob/main/WhirlEdit.py)

**Comment by ayuvius** [comment]
okay okay..
it worked..
i just did a stupid mistake in my program.. lol
anyways.. thanks for your active help..
