### ISSUE TITLE
Push improvements

### ISSUE THREAD

**Issue by rdbende** [rdbende/tkcode#8]
This is a reminder for me, to finally push the changes that have been sitting in my local repo for 2-3 months.

**Comment by Moosems** [comment]
I'm ready!

<img src="https://y.yarn.co/b89ba957-599d-4060-8d08-265c46d02d4f_text.gif">

**Comment by rdbende** [comment]
Figured out why I haven't pushed the fixes yet. The new syntax highlighting mechanism has problems with pasting.
