### ISSUE TITLE
Make syntax highlight automatically

### ISSUE THREAD

**Issue by Moosems** [rdbende/tkcode#9]
I've noticed as I type that the syntax takes a moment or two to add the syntax highlighting. I suspect this is due to [this line](https://github.com/rdbende/tkcode/blob/9873f672477fd7cfcaf6b3cb0b535a283d9b127b/tkcode/codeeditor.py#L45) using the keyrelease. Given that the user must wait for the character to be inserted visually before it can be read this poses a challenge

**Comment by rdbende** [comment]
LOL 😆 (see #8).
Someone already reported this problem by email, about 2 months ago, and I even fixed it so that the delay is barely noticeable. I just didn't have time to push it? Or idk what happened with it 😂

**Comment by Moosems** [comment]
Lol

**Comment by Moosems** [comment]
I just made some edits on my own end and got it to instantly highlight. I'll make a pull request to add it
